### ISSUE TITLE
Upgrade to VimClojure 2.3.4

### ISSUE THREAD

**Issue by ctford** [daveray/vimclojure-easy#12]
There's a new bugfix release out:

http://www.vim.org/scripts/script.php?script_id=2501

I'll submit a pull request when I've sorted out the "resultBuffer" problem I've come across while upgrading.

**Comment by daveray** [comment]
Make that 2.3.5 which Meikel just released to address the resultbuffer thing. :)

**Comment by ctford** [comment]
Closing this in favour of #13, a pull request for 2.3.5.
