### ISSUE TITLE
"lein vimclojure" Fails on Linux Mint: Could not locate trammel/core__init.class or trammel/core.clj on classpath

### ISSUE THREAD

**Issue by joaopimentel** [daveray/vimclojure-easy#16]
I've been trying to make the nailgun work, but I can't seem to be able to do so. Following every step as in the README, and when I get to the "lein vimclojure", it fails. Syntax highlighting is OK.

Running on Linux Mint 12
Any idea what may be happening?
My system's CLASSPATH is empty. Should it be different?

$ lein -v
Leiningen 1.6.1 on Java 1.6.0_24 OpenJDK 64-Bit Server VM

$ lein classpath
/home/jpimentel/nailgun-test/test:/home/jpimentel/nailgun-test/test-resources:/home/jpimentel/nailgun-test/src:/home/jpimentel/nailgun-test/classes:/home/jpimentel/nailgun-test/resources:/home/jpimentel/.lein/plugins/lein-tarsier-0.9.1.jar

$ lein vimclojure
Exception in thread "main" java.io.FileNotFoundException: Could not locate trammel/core__init.class or trammel/core.clj on classpath:  (vimclojure.clj:1)
[big stack trace then]

**Comment by daveray** [comment]
Sorry I haven't updated this yet. vimclojure has kind of been deprecated and replaced by foreplay.vim. Set up is more straightforward although you'll have to use Leiningent 2. There's a tutorial/reference here: http://clojure-doc.org/articles/tutorials/vim_foreplay.html

**Comment by joaopimentel** [comment]
Thank you! I'll check foreplay.vim then ;)
