### ISSUE TITLE
Installing ng server bonks lein

### ISSUE THREAD

**Issue by ghost** [daveray/vimclojure-easy#3]
After doing

```
lein plugin install org.clojars.ibdknox/lein-nailgun "1.1.1"
```

All attempts at using lein crash with a long error beginning with

```
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodError: clojure.lang.KeywordLookupSite.<init>(ILclojure/lang/Keyword;)V
```

**Comment by daveray** [comment]
Do you know what version of lein you're running?

**Comment by ghost** [comment]
1.7.0 
It's the current version on Homebrew.

**Comment by daveray** [comment]
Hmmm.. I was using 1.6.2, but just upgraded to 1.7.0 and didn't have any issues. I also deleted the plugin:

```
 rm ~/.lein/plugins/org.clojars.ibdknox-lein-nailgun-1.1.1.jar 
```

and reinstalled it without problems. I'm using a manual installation of lein, not from homebrew or anything. I'm not sure if that makes a difference.

I guess try deleting the plugin, see if that brings your lein back to life and try installing it again?

There are also several SO questions with this issue: http://stackoverflow.com/questions/7996380/leiningen-not-working-on-os-x

**Comment by ghost** [comment]
While messing with lein, I noticed that it has a lein nailgun command that runs a ng server. I tried it and it seems to be work perfectly. Does this replace the nailgun server plugin?

**Comment by daveray** [comment]
Hey. The "lein nailgun" command _is_ the nailgun server plugin. When
the plugin's installed, that command becomes available. Sounds like
you got it working.

On Tue, Mar 20, 2012 at 1:06 AM, autodidakto
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
Ahh. I uninstalled lein, then reintalled it without nuking the plugin. Hmm, I guess we can call it closed, but I wish I got to the bottom of it.

**Comment by daveray** [comment]
cool.
