### ISSUE TITLE
Setting path correctly for "GotoSourceWord[Interactive]"

### ISSUE THREAD

**Issue by ghost** [daveray/vimclojure-easy#6]
I'm trying to use GotoSourceWord (<leader>gw) to quickly jump to function definitions. This works great inside the same file, but looking up a definition in another file gets me "Vim(echoerr):0 not found in 'path'". I've tried different settings for path, but I can't seem to make it work.

**Comment by daveray** [comment]
I've never actually used this feature :)

But, I just played around with it a bit and it seems to kind of work. In a vanilla lein project, I did this:

```
$ export CLOJURE_SOURCE_DIRS=src
$ vim
```

and it seemed to work.

For further info, I'd suggest asking on the vimclojure mailing list. Meikel knows a lot more about vimclojure than I do: https://groups.google.com/group/vimclojure

**Comment by ghost** [comment]
Ah. Thank you :) I'll play around with that and join the group. Sorry about the tech support needs.

**Comment by daveray** [comment]
No problem. Thanks for using vimclojure :)

**Comment by ghost** [comment]
So here are my findings. To get GotoSourceWord to work, you need your add your projects source files in your path. So, I added this to my .vimrc:

```
set path+=src/**,test/**
```

This assumes that you working directory is the root of your lein project.

If DocWordLookup isn't enough and you want to view the clojure source: To get SourceLookupWord working download the clojure source, extract, find the clojure dir (it has core.clj) and point the variable at it in your bash/zshrc:

```
export CLOJURE_SOURCE_DIRS="~/clojure-source/clojure"
```

I hope you can add this to the README somehow. Or if you want, I can fork and edit :)
