### ISSUE TITLE
New nailgun server/plugin

### ISSUE THREAD

**Issue by ghost** [daveray/vimclojure-easy#7]
A new nailgun plugin came out. It supports lein2, it has a repl that connects to the server. Check it out. I think it's a replacement for ibdknox's older plugin.

https://github.com/sattvik/lein-tarsier

**Comment by daveray** [comment]
Thanks. It's at the top of my todo list :)

**Comment by daveray** [comment]
Done. :)

**Comment by ghost** [comment]
Most awesome. Thanks.
